# SITE SETUP
# Guide: https://docs.hugoblox.com/tutorial/
# Documentation: https://docs.hugoblox.com/
# This file is formatted using YAML syntax - learn more at https://learnxinyminutes.com/docs/yaml/

# Appearance
appearance:
  mode: light
  color: green

# SEO
marketing:
  seo:
    site_type: Business
    local_business_type: ''
    org_name: 'OpenProductions Kft and Reprex BV'
    description: 'Trustworthy AI to build ESG reports from your financial bookkeeping.'
    twitter: ''
  analytics:
    google_analytics: ''
    baidu_tongji: ''
    plausible: ''
    fathom: ''
    pirsch: ''
  verification:
    google: ''
    baidu: ''

# Site header
header:
  navbar:
    enable: true
    blox: "navbar"
    align: "center"
    fixed_to_top: true
    logo:
      text: ""
      # Logo filename in `assets/media/` folder
      filename: "OpenProduction_logo.svg"
    button:
      enable: true
      text: "Get in touch"
      url: "https://reprex.nl/contact/"
    show_search: true
    show_theme_chooser: true

# Site footer
footer:
  copyright:
    notice: '© {year} OpenProductions Kft, Reprex B.V.'

# Localization
locale:
  date_format: 'Jan 2, 2006'
  time_format: '3:04 PM'
